### ISSUE TITLE
Write a state file with the machine provisioned, its ID and auth token

### ISSUE THREAD

**Issue by alexellis** [inlets/inletsctl#28]
This feature will write a state file with the machine provisioned, its ID and auth token

## Expected Behaviour

A file (probably YAML file) should be written to disk after provisioning a host, it will be used by the user to be able to delete or reconnect to the host at a later date, it's especially useful if the auth token, ID or IP was lost.

## Current Behaviour

In this scenario, I have to delete / re-create, or ssh into the exit server after doing a password reset.

## Possible Solution

Write a file such as `host-name-inletsctl.yaml` with:

```yaml
host:
  metadata:
    created_at: A
    provider: B
    region: C
  ip: Y
  id : Z
  auth_token: A
  pro: true/false
```

Initially, this will not be consumable by the CLI itself, but will act like a state file or reminder for the user.

**Comment by alexellis** [comment]
@adamjohnson01 WDYT?

**Comment by Waterdrips** [comment]
I would love this - possibly a command to give you the inlets command for a specific host, could we name them too?

**Comment by adamjohnson01** [comment]
@alexellis I think this is a great idea. I would be happy to take it on.

**Comment by alexellis** [comment]
Yes sounds good, please take it Adam. Any input on how it should work or did this sound like a good first pass?

**Comment by adamjohnson01** [comment]
I like the idea about a commend that will give you the inlets command for the specific host if users are going to have multiple inlets then I think a single file that contains a list would be the way to go with potentially an easy to remember or descriptive name? Something like this? 

```
hosts:
  - name: generated name or alias if set by user?
     metadata:
       created_at: A
       provider: B
       region: C
    ip: Y
    id : Z
    auth_token: A
    pro: true/false
```

I will get the file generation working and we can go from there.
